name: organizate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 칈conos
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9

  # Fechas y localizaci칩n en espa침ol
  intl: ^0.19.0

  # Guardar datos locales (tema, notificaciones activas, etc.)
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4        # LOGIN
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.2     # Para subir fotos en el futuro

  # UI / Gr치ficos
  fl_chart: ^1.1.1

  # Notificaciones locales
  flutter_local_notifications: ^17.1.0

  # Manejo de estado (칰til para avatar, usuario, settings)
  provider: ^6.1.2

  # 游댉 AUDIO PARA POMODORO Y EJERCICIOS DE RELAJACI칍N
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/icons/
    - assets/images/Logo.png
    - assets/sounds/           # <--- NUEVO (carpeta donde estar치 bell.mp3)


